### PR TITLE
Update object cache drop-in links

### PR DESCRIPTION
**Pull request by tillkruss**
I took the liberty to update the links back to the original and fix my name 🙃

### CODE REVIEW

**Comment by tillkruss** [comment]
It might also make sense to merge your customizations back into the original and deploy that, instead of merging upstream changes all the time. That would also enable CLI commands and other benefits.

**Comment by gilbitron** [comment]
@tillkruss Thanks for this PR and your awesome work on the Redis Object Cache plugin. 

We didn't think about merging our changes upstream as they're specific to our use case/setup. The only minor changes we've made are to deprecate a couple of constants and add some of our own:

* https://github.com/deliciousbrains/spinupwp-plugin/commit/7cc2b8c68cb3ff886431bdfe8511657f6503ac67#diff-7a6f8824a65ef07bbf979f8281d374c9
* https://github.com/deliciousbrains/spinupwp-plugin/commit/b28286e30bf65e48eea2b04cc51809d154a0808c#diff-7a6f8824a65ef07bbf979f8281d374c9

However, if you think is something we can work with then let us know?

Also, we weren't sure what you meant by "enabling CLI commands and other benefits". Can you explain what you mean?

**Comment by tillkruss** [comment]
Cool, supporting `SPINUPWP_CACHE_KEY_SALT` as constant and `getenv()` is easy.

SpinupWP only shipping the `object-cache.php` drop-in means that:

- It can't be easily activated/deactivate via the Dashboard
- No overview of the used settings (MaxTTL, prefix, etc.)
- The WP CLI commands don't work (`wp redis status` etc.)
- No [Redis metrics](https://github.com/rhubarbgroup/redis-cache#redis-object-cache-for-wordpress) for users
- No Query Monitor or Debug Bar integration for debugging

Does that make sense? I'm happy to make the necessary adjustments to make it seamless to integrate.

**Comment by A5hleyRich** [comment]
Hey @tillkruss, that makes total sense. We already install Limit Login Attempts Reloaded from the WP repo for SpinupWP sites, so it would be awesome if we could also install Redis Object Cache if the ENV vars are added.

**Comment by tillkruss** [comment]
@A5hleyRich Fantastic! Let's continue this conversation here: https://github.com/rhubarbgroup/redis-cache/pull/280

**Pull request merged**
